In [3]:
import numpy as np

In [45]:
x = np.arange(1,101,1)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
x[0:101:3]

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [12]:
x[::-1][0:91:3]

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [46]:
k = np.arange(1,101)
k


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [40]:
k[21:30:1]

array([22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
k[29:50]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50])

In [50]:
k[9:31]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31])

In [15]:
k[9:14:]

array([10, 11, 12, 13, 14])

In [9]:
k[15::]

array([ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [10]:
k.sum()

5050

In [11]:
k.mean()

50.5

In [12]:
k.std()

28.86607004772212

In [38]:
x = np.random.randint(1,7)
x

1

In [35]:
y = np.random.randint(1,101,10)
y

array([ 6, 34, 92, 63, 16, 51, 97, 63, 10, 76])

In [38]:
y.sum()

508

In [39]:
y.mean()

50.8

In [40]:
y.std()

31.51126782596981

In [41]:
y.max()

97

In [42]:
y.min()

6

In [45]:
c = np.array([68,50,70,75,75,80])

In [47]:
b = c.argmax()
print('電費最多月份：',b+1)

電費最多月份： 6


In [49]:
q = c.argmin()
print('電費最低月份：',q+1)

電費最低月份： 2


In [61]:
s = np.array([64,25,49,81])
f = np.sqrt(s)*10
f

array([80., 50., 70., 90.])

AttributeError: 'numpy.ndarray' object has no attribute 'np'