In [16]:
#第一題：(1)
n = int(input('請輸入數字：'))
while n<10:
    x = 1
    for i in range(1, n+1):
        x = x * i
    print(x)
    break


請輸入數字：5
120


In [1]:
#第一題：(2)
n = int(input('請輸入數字：'))
total = 0
x = 1
for i in range(1, n+1):
    x = x*i
    total = total + x
print(total)

請輸入數字：5
153


In [40]:
#第二題：
total = 0

for i in range(1,101):
    total = total + i
print(total)

total_2 = 0
for k in range(6,97,10):
    total_2 = total_2 + k
print(total_2)

answer = total - total_2
print(answer)

5050
510
4540


In [5]:
#第二題：第二種寫法
total = 0
for i in range(1 ,101):
    if (i+4)%10 == 0:
        continue 
    total = total + i
    
print(total)

4540


In [5]:
#第三題：第一種寫法  
while True:
    chinese = float(input('請輸入國文成績：'))
    math = float(input('請輸入數學成績：'))
    total = chinese + math 
    print(total)
    avg = (chinese+math)/2
    if 90 <= avg:
        print('A')
    elif 80 <= avg < 90:
        print('B')
    elif 70 <= avg < 80:
        print('C')
    elif 60 <= avg < 70:
        print('D')
    elif avg < 60:
        print('E')
    

KeyboardInterrupt: 

In [19]:
#第三題：第二種寫法
import numpy as np
while True:
    chinese = int(input('請輸入國文成績：'))
    math = int(input('請輸入數學成績：'))
    if 0 <= chinese <= 100 and 0 <= math <= 100:
        score = np.array([chinese,math])
        total = score.sum()
        print('總成績：',total)
        avg = score.mean()
        if 90 <= avg:
            print('平均數為:', avg,'故為A')
        elif 80 <= avg <= 89:
            print('平均數為:', avg, '故為B')
        elif 70 <= avg <= 79:
            print('平均數為:', avg, '故為C')
        elif 60 <= avg <= 69:
            print('平均數為:', avg, '故為D')
        elif avg <= 59:
            print('平均數為:', avg, '故為E')
    else:
        print('請重新輸入')


請輸入國文成績：80
請輸入數學成績：70
總成績： 150
平均數為: 75.0 故為C
請輸入國文成績：74
請輸入數學成績：68
總成績： 142
平均數為: 71.0 故為C


KeyboardInterrupt: 

In [6]:
#第四題
import numpy as np
#第一小題：
score = np.array([[60,76],[66,68],[70,80],[72,66],[90,70]])
#第二小題：
score[2,0] = 81
score[2][0] = 81
score




array([[60, 76],
       [66, 68],
       [81, 80],
       [72, 66],
       [90, 70]])

In [8]:
#第三小題：
import numpy as np
score = np.array([[60,76],
                  [66,68],
                  [70,80],
                  [72,66],
                  [90,70]])
score[2,0] = 81
score_2 = score.sum(1)
-np.sort(-score_2)

array([-134, -136, -138, -160, -161])

In [62]:
#第四小題：  #改
import numpy as np
score = np.array([[60,76],
                  [66,68],
                  [70,80],
                  [72,66],
                  [90,70]])
score[2,0] = 81
print(score.sum(1))
#使列加總結果成為新變數score_2
score_2 = score.sum(1)
n = 0
dict = {score_2[n]:n+1,
        score_2[n+1]:'2號',
        score_2[n+2]:'3號',
        score_2[n+3]:'4號',
        score_2[n+4]:'5號'}
print(dict)
dict_2 = list(dict.items())
dict_2.sort()
dict_2

[136 134 161 138 160]
{136: 1, 134: '2號', 161: '3號', 138: '4號', 160: '5號'}


[(134, '2號'), (136, 1), (138, '4號'), (160, '5號'), (161, '3號')]

In [29]:
import numpy as np
score = np.array([[60,76],
                  [66,68],
                  [70,80],
                  [72,66],
                  [90,70]])
score[2,0] = 81
score_2 = score.sum(1)
#利用enumerate給予編號
score_3 = list(enumerate(score_2, start = 1))
print(score_3)

#把key-value反轉
score_4 = {value:key for key,value in score_3}
print(score_4)

#利用字典的排序 sorted
sorted(score_4.items())

[(1, 136), (2, 134), (3, 161), (4, 138), (5, 160)]
{136: 1, 134: 2, 161: 3, 138: 4, 160: 5}


[(134, 2), (136, 1), (138, 4), (160, 5), (161, 3)]

In [20]:
#list index用法
list = [136, 134, 161, 138, 160]
print(list.index(161)+1)

3


In [10]:
#第五題：
import random
while True:
    you = input('請輸入剪刀/石頭/布/結束：')
    if you == '剪刀' or you == '石頭' or you == '布':
        computer = random.choice(['剪刀','石頭','布'])
        print('電腦出了', computer)
        if you == computer:
            print('平手！')
        if you == '剪刀':
            if computer == '石頭':
                print('你輸了')
            elif computer == '布':
                print('你贏了')
        if you == '石頭':
            if computer == '布':
                print('你輸了')
            if computer == '剪刀':
                print('你贏了')
        if you == '布':
            if computer == '剪刀':
                print('你輸了')
            if computer == '石頭':
                print('你贏了')
    elif you == '結束':
            break
    else:
        print('請重新輸入')

請輸入剪刀/石頭/布/結束：剪刀
電腦出了 剪刀
平手！
請輸入剪刀/石頭/布/結束：石頭
電腦出了 剪刀
你贏了
請輸入剪刀/石頭/布/結束：布
電腦出了 剪刀
你輸了
請輸入剪刀/石頭/布/結束：我我我
請重新輸入
請輸入剪刀/石頭/布/結束：結束


In [12]:
password = 'a123'
i = 3
while True:
    pwd = input('請輸入數字：')
    i = i - 1
    if pwd == password:
        print('歡迎你回來')
        break
    else:
        print('請重新輸入，你還剩', i , '次機會')
        if i == 0:
            print('你的機會用完了')
            break
            

請輸入數字：a344
請重新輸入，你還剩 2 次機會
請輸入數字：a123
歡迎你回來
